/*
 * This class file was automatically generated by ASN1bean v1.12.0 (http://www.beanit.com)
 */

package pgw;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class ContentInfo implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static class ServiceList implements BerType, Serializable {

		private static final long serialVersionUID = 1L;

		public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);
		private byte[] code = null;
		private List<ServiceEvent> seqOf = null;

		public ServiceList() {
			seqOf = new ArrayList<ServiceEvent>();
		}

		public ServiceList(byte[] code) {
			this.code = code;
		}

		public List<ServiceEvent> getServiceEvent() {
			if (seqOf == null) {
				seqOf = new ArrayList<ServiceEvent>();
			}
			return seqOf;
		}

		@Override public int encode(OutputStream reverseOS) throws IOException {
			return encode(reverseOS, true);
		}

		public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

			if (code != null) {
				reverseOS.write(code);
				if (withTag) {
					return tag.encode(reverseOS) + code.length;
				}
				return code.length;
			}

			int codeLength = 0;
			for (int i = (seqOf.size() - 1); i >= 0; i--) {
				codeLength += seqOf.get(i).encode(reverseOS, true);
			}

			codeLength += BerLength.encodeLength(reverseOS, codeLength);

			if (withTag) {
				codeLength += tag.encode(reverseOS);
			}

			return codeLength;
		}

		@Override public int decode(InputStream is) throws IOException {
			return decode(is, true);
		}

		public int decode(InputStream is, boolean withTag) throws IOException {
			int tlByteCount = 0;
			int vByteCount = 0;
			BerTag berTag = new BerTag();
			if (withTag) {
				tlByteCount += tag.decodeAndCheck(is);
			}

			BerLength length = new BerLength();
			tlByteCount += length.decode(is);
			int lengthVal = length.val;

			while (vByteCount < lengthVal || lengthVal < 0) {
				vByteCount += berTag.decode(is);

				if (lengthVal < 0 && berTag.equals(0, 0, 0)) {
					vByteCount += BerLength.readEocByte(is);
					break;
				}

				if (!berTag.equals(ServiceEvent.tag)) {
					throw new IOException("Tag does not match mandatory sequence of/set of component.");
				}
				ServiceEvent element = new ServiceEvent();
				vByteCount += element.decode(is, false);
				seqOf.add(element);
			}
			if (lengthVal >= 0 && vByteCount != lengthVal) {
				throw new IOException("Decoded SequenceOf or SetOf has wrong length. Expected " + lengthVal + " but has " + vByteCount);

			}
			return tlByteCount + vByteCount;
		}

		public void encodeAndSave(int encodingSizeGuess) throws IOException {
			ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
			encode(reverseOS, false);
			code = reverseOS.getArray();
		}

		@Override public String toString() {
			StringBuilder sb = new StringBuilder();
			appendAsString(sb, 0);
			return sb.toString();
		}

		public void appendAsString(StringBuilder sb, int indentLevel) {

			sb.append("{\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			if (seqOf == null) {
				sb.append("null");
			}
			else {
				Iterator<ServiceEvent> it = seqOf.iterator();
				if (it.hasNext()) {
					it.next().appendAsString(sb, indentLevel + 1);
					while (it.hasNext()) {
						sb.append(",\n");
						for (int i = 0; i < indentLevel + 1; i++) {
							sb.append("\t");
						}
						it.next().appendAsString(sb, indentLevel + 1);
					}
				}
			}

			sb.append("\n");
			for (int i = 0; i < indentLevel; i++) {
				sb.append("\t");
			}
			sb.append("}");
		}

	}

	public static class ChangeTimeList implements BerType, Serializable {

		private static final long serialVersionUID = 1L;

		public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);
		private byte[] code = null;
		private List<ChangeTimeExtension> seqOf = null;

		public ChangeTimeList() {
			seqOf = new ArrayList<ChangeTimeExtension>();
		}

		public ChangeTimeList(byte[] code) {
			this.code = code;
		}

		public List<ChangeTimeExtension> getChangeTimeExtension() {
			if (seqOf == null) {
				seqOf = new ArrayList<ChangeTimeExtension>();
			}
			return seqOf;
		}

		@Override public int encode(OutputStream reverseOS) throws IOException {
			return encode(reverseOS, true);
		}

		public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

			if (code != null) {
				reverseOS.write(code);
				if (withTag) {
					return tag.encode(reverseOS) + code.length;
				}
				return code.length;
			}

			int codeLength = 0;
			for (int i = (seqOf.size() - 1); i >= 0; i--) {
				codeLength += seqOf.get(i).encode(reverseOS, true);
			}

			codeLength += BerLength.encodeLength(reverseOS, codeLength);

			if (withTag) {
				codeLength += tag.encode(reverseOS);
			}

			return codeLength;
		}

		@Override public int decode(InputStream is) throws IOException {
			return decode(is, true);
		}

		public int decode(InputStream is, boolean withTag) throws IOException {
			int tlByteCount = 0;
			int vByteCount = 0;
			BerTag berTag = new BerTag();
			if (withTag) {
				tlByteCount += tag.decodeAndCheck(is);
			}

			BerLength length = new BerLength();
			tlByteCount += length.decode(is);
			int lengthVal = length.val;

			while (vByteCount < lengthVal || lengthVal < 0) {
				vByteCount += berTag.decode(is);

				if (lengthVal < 0 && berTag.equals(0, 0, 0)) {
					vByteCount += BerLength.readEocByte(is);
					break;
				}

				if (!berTag.equals(ChangeTimeExtension.tag)) {
					throw new IOException("Tag does not match mandatory sequence of/set of component.");
				}
				ChangeTimeExtension element = new ChangeTimeExtension();
				vByteCount += element.decode(is, false);
				seqOf.add(element);
			}
			if (lengthVal >= 0 && vByteCount != lengthVal) {
				throw new IOException("Decoded SequenceOf or SetOf has wrong length. Expected " + lengthVal + " but has " + vByteCount);

			}
			return tlByteCount + vByteCount;
		}

		public void encodeAndSave(int encodingSizeGuess) throws IOException {
			ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
			encode(reverseOS, false);
			code = reverseOS.getArray();
		}

		@Override public String toString() {
			StringBuilder sb = new StringBuilder();
			appendAsString(sb, 0);
			return sb.toString();
		}

		public void appendAsString(StringBuilder sb, int indentLevel) {

			sb.append("{\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			if (seqOf == null) {
				sb.append("null");
			}
			else {
				Iterator<ChangeTimeExtension> it = seqOf.iterator();
				if (it.hasNext()) {
					it.next().appendAsString(sb, indentLevel + 1);
					while (it.hasNext()) {
						sb.append(",\n");
						for (int i = 0; i < indentLevel + 1; i++) {
							sb.append("\t");
						}
						it.next().appendAsString(sb, indentLevel + 1);
					}
				}
			}

			sb.append("\n");
			for (int i = 0; i < indentLevel; i++) {
				sb.append("\t");
			}
			sb.append("}");
		}

	}

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	private byte[] code = null;
	private BerInteger extensionType = null;
	private BerInteger lengthh = null;
	private ServiceList serviceList = null;
	private ChangeTimeList changeTimeList = null;
	private BerOctetString recordOpeningTime = null;
	private BerOctetString duration = null;
	private BerOctetString transparentVSA = null;
	private BerBoolean cdrType = null;
	private BerOctetString createTime = null;
	private BerInteger chargingType = null;
	private BerBoolean roaming = null;
	private BerInteger profile = null;
	private BerInteger nsapi = null;
	private BerOctetString lastActivityTimeUpLink = null;
	private BerOctetString lastActivityTimeDownLink = null;
	private BerInteger zoneId = null;
	private BerInteger daylightSavingTime = null;
	private BerInteger localTimeZone = null;
	private BerBoolean sgsnChange = null;
	private BerInteger sessionID = null;
	private BerInteger recordOpeningTimeZone = null;
	private BerOctetString saRecordChangeTime = null;
	private BerInteger saRecordChangeTimeZone = null;
	private BerOctetString acctSessionId = null;
	private BerInteger acctTerminateCause = null;
	
	public ContentInfo() {
	}

	public ContentInfo(byte[] code) {
		this.code = code;
	}

	public void setExtensionType(BerInteger extensionType) {
		this.extensionType = extensionType;
	}

	public BerInteger getExtensionType() {
		return extensionType;
	}

	public void setLengthh(BerInteger lengthh) {
		this.lengthh = lengthh;
	}

	public BerInteger getLengthh() {
		return lengthh;
	}

	public void setServiceList(ServiceList serviceList) {
		this.serviceList = serviceList;
	}

	public ServiceList getServiceList() {
		return serviceList;
	}

	public void setChangeTimeList(ChangeTimeList changeTimeList) {
		this.changeTimeList = changeTimeList;
	}

	public ChangeTimeList getChangeTimeList() {
		return changeTimeList;
	}

	public void setRecordOpeningTime(BerOctetString recordOpeningTime) {
		this.recordOpeningTime = recordOpeningTime;
	}

	public BerOctetString getRecordOpeningTime() {
		return recordOpeningTime;
	}

	public void setDuration(BerOctetString duration) {
		this.duration = duration;
	}

	public BerOctetString getDuration() {
		return duration;
	}

	public void setTransparentVSA(BerOctetString transparentVSA) {
		this.transparentVSA = transparentVSA;
	}

	public BerOctetString getTransparentVSA() {
		return transparentVSA;
	}

	public void setCdrType(BerBoolean cdrType) {
		this.cdrType = cdrType;
	}

	public BerBoolean getCdrType() {
		return cdrType;
	}

	public void setCreateTime(BerOctetString createTime) {
		this.createTime = createTime;
	}

	public BerOctetString getCreateTime() {
		return createTime;
	}

	public void setChargingType(BerInteger chargingType) {
		this.chargingType = chargingType;
	}

	public BerInteger getChargingType() {
		return chargingType;
	}

	public void setRoaming(BerBoolean roaming) {
		this.roaming = roaming;
	}

	public BerBoolean getRoaming() {
		return roaming;
	}

	public void setProfile(BerInteger profile) {
		this.profile = profile;
	}

	public BerInteger getProfile() {
		return profile;
	}

	public void setNsapi(BerInteger nsapi) {
		this.nsapi = nsapi;
	}

	public BerInteger getNsapi() {
		return nsapi;
	}

	public void setLastActivityTimeUpLink(BerOctetString lastActivityTimeUpLink) {
		this.lastActivityTimeUpLink = lastActivityTimeUpLink;
	}

	public BerOctetString getLastActivityTimeUpLink() {
		return lastActivityTimeUpLink;
	}

	public void setLastActivityTimeDownLink(BerOctetString lastActivityTimeDownLink) {
		this.lastActivityTimeDownLink = lastActivityTimeDownLink;
	}

	public BerOctetString getLastActivityTimeDownLink() {
		return lastActivityTimeDownLink;
	}

	public void setZoneId(BerInteger zoneId) {
		this.zoneId = zoneId;
	}

	public BerInteger getZoneId() {
		return zoneId;
	}

	public void setDaylightSavingTime(BerInteger daylightSavingTime) {
		this.daylightSavingTime = daylightSavingTime;
	}

	public BerInteger getDaylightSavingTime() {
		return daylightSavingTime;
	}

	public void setLocalTimeZone(BerInteger localTimeZone) {
		this.localTimeZone = localTimeZone;
	}

	public BerInteger getLocalTimeZone() {
		return localTimeZone;
	}

	public void setSgsnChange(BerBoolean sgsnChange) {
		this.sgsnChange = sgsnChange;
	}

	public BerBoolean getSgsnChange() {
		return sgsnChange;
	}

	public void setSessionID(BerInteger sessionID) {
		this.sessionID = sessionID;
	}

	public BerInteger getSessionID() {
		return sessionID;
	}

	public void setRecordOpeningTimeZone(BerInteger recordOpeningTimeZone) {
		this.recordOpeningTimeZone = recordOpeningTimeZone;
	}

	public BerInteger getRecordOpeningTimeZone() {
		return recordOpeningTimeZone;
	}

	public void setSaRecordChangeTime(BerOctetString saRecordChangeTime) {
		this.saRecordChangeTime = saRecordChangeTime;
	}

	public BerOctetString getSaRecordChangeTime() {
		return saRecordChangeTime;
	}

	public void setSaRecordChangeTimeZone(BerInteger saRecordChangeTimeZone) {
		this.saRecordChangeTimeZone = saRecordChangeTimeZone;
	}

	public BerInteger getSaRecordChangeTimeZone() {
		return saRecordChangeTimeZone;
	}

	public void setAcctSessionId(BerOctetString acctSessionId) {
		this.acctSessionId = acctSessionId;
	}

	public BerOctetString getAcctSessionId() {
		return acctSessionId;
	}

	public void setAcctTerminateCause(BerInteger acctTerminateCause) {
		this.acctTerminateCause = acctTerminateCause;
	}

	public BerInteger getAcctTerminateCause() {
		return acctTerminateCause;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (acctTerminateCause != null) {
			codeLength += acctTerminateCause.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 27
			reverseOS.write(0x9B);
			codeLength += 1;
		}
		
		if (acctSessionId != null) {
			codeLength += acctSessionId.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 26
			reverseOS.write(0x9A);
			codeLength += 1;
		}
		
		if (saRecordChangeTimeZone != null) {
			codeLength += saRecordChangeTimeZone.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 22
			reverseOS.write(0x96);
			codeLength += 1;
		}
		
		if (saRecordChangeTime != null) {
			codeLength += saRecordChangeTime.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 21
			reverseOS.write(0x95);
			codeLength += 1;
		}
		
		if (recordOpeningTimeZone != null) {
			codeLength += recordOpeningTimeZone.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 20
			reverseOS.write(0x94);
			codeLength += 1;
		}
		
		if (sessionID != null) {
			codeLength += sessionID.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 19
			reverseOS.write(0x93);
			codeLength += 1;
		}
		
		if (sgsnChange != null) {
			codeLength += sgsnChange.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 18
			reverseOS.write(0x92);
			codeLength += 1;
		}
		
		if (localTimeZone != null) {
			codeLength += localTimeZone.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 17
			reverseOS.write(0x91);
			codeLength += 1;
		}
		
		if (daylightSavingTime != null) {
			codeLength += daylightSavingTime.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 16
			reverseOS.write(0x90);
			codeLength += 1;
		}
		
		if (zoneId != null) {
			codeLength += zoneId.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 15
			reverseOS.write(0x8F);
			codeLength += 1;
		}
		
		if (lastActivityTimeDownLink != null) {
			codeLength += lastActivityTimeDownLink.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 14
			reverseOS.write(0x8E);
			codeLength += 1;
		}
		
		if (lastActivityTimeUpLink != null) {
			codeLength += lastActivityTimeUpLink.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 13
			reverseOS.write(0x8D);
			codeLength += 1;
		}
		
		if (nsapi != null) {
			codeLength += nsapi.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 12
			reverseOS.write(0x8C);
			codeLength += 1;
		}
		
		if (profile != null) {
			codeLength += profile.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 11
			reverseOS.write(0x8B);
			codeLength += 1;
		}
		
		if (roaming != null) {
			codeLength += roaming.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 10
			reverseOS.write(0x8A);
			codeLength += 1;
		}
		
		if (chargingType != null) {
			codeLength += chargingType.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 9
			reverseOS.write(0x89);
			codeLength += 1;
		}
		
		if (createTime != null) {
			codeLength += createTime.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 8
			reverseOS.write(0x88);
			codeLength += 1;
		}
		
		if (cdrType != null) {
			codeLength += cdrType.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 7
			reverseOS.write(0x87);
			codeLength += 1;
		}
		
		if (transparentVSA != null) {
			codeLength += transparentVSA.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 6
			reverseOS.write(0x86);
			codeLength += 1;
		}
		
		if (duration != null) {
			codeLength += duration.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 5
			reverseOS.write(0x85);
			codeLength += 1;
		}
		
		if (recordOpeningTime != null) {
			codeLength += recordOpeningTime.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 4
			reverseOS.write(0x84);
			codeLength += 1;
		}
		
		if (changeTimeList != null) {
			codeLength += changeTimeList.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 3
			reverseOS.write(0xA3);
			codeLength += 1;
		}
		
		if (serviceList != null) {
			codeLength += serviceList.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 2
			reverseOS.write(0xA2);
			codeLength += 1;
		}
		
		codeLength += lengthh.encode(reverseOS, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 1
		reverseOS.write(0x81);
		codeLength += 1;
		
		codeLength += extensionType.encode(reverseOS, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 0
		reverseOS.write(0x80);
		codeLength += 1;
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int tlByteCount = 0;
		int vByteCount = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			tlByteCount += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		tlByteCount += length.decode(is);
		int lengthVal = length.val;
		vByteCount += berTag.decode(is);

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
			extensionType = new BerInteger();
			vByteCount += extensionType.decode(is, false);
			vByteCount += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match mandatory sequence component.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			lengthh = new BerInteger();
			vByteCount += lengthh.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match mandatory sequence component.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 2)) {
			serviceList = new ServiceList();
			vByteCount += serviceList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 3)) {
			changeTimeList = new ChangeTimeList();
			vByteCount += changeTimeList.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 4)) {
			recordOpeningTime = new BerOctetString();
			vByteCount += recordOpeningTime.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 5)) {
			duration = new BerOctetString();
			vByteCount += duration.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 6)) {
			transparentVSA = new BerOctetString();
			vByteCount += transparentVSA.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 7)) {
			cdrType = new BerBoolean();
			vByteCount += cdrType.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 8)) {
			createTime = new BerOctetString();
			vByteCount += createTime.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 9)) {
			chargingType = new BerInteger();
			vByteCount += chargingType.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 10)) {
			roaming = new BerBoolean();
			vByteCount += roaming.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 11)) {
			profile = new BerInteger();
			vByteCount += profile.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 12)) {
			nsapi = new BerInteger();
			vByteCount += nsapi.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 13)) {
			lastActivityTimeUpLink = new BerOctetString();
			vByteCount += lastActivityTimeUpLink.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 14)) {
			lastActivityTimeDownLink = new BerOctetString();
			vByteCount += lastActivityTimeDownLink.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 15)) {
			zoneId = new BerInteger();
			vByteCount += zoneId.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 16)) {
			daylightSavingTime = new BerInteger();
			vByteCount += daylightSavingTime.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 17)) {
			localTimeZone = new BerInteger();
			vByteCount += localTimeZone.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 18)) {
			sgsnChange = new BerBoolean();
			vByteCount += sgsnChange.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 19)) {
			sessionID = new BerInteger();
			vByteCount += sessionID.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 20)) {
			recordOpeningTimeZone = new BerInteger();
			vByteCount += recordOpeningTimeZone.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 21)) {
			saRecordChangeTime = new BerOctetString();
			vByteCount += saRecordChangeTime.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 22)) {
			saRecordChangeTimeZone = new BerInteger();
			vByteCount += saRecordChangeTimeZone.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 26)) {
			acctSessionId = new BerOctetString();
			vByteCount += acctSessionId.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 27)) {
			acctTerminateCause = new BerInteger();
			vByteCount += acctTerminateCause.decode(is, false);
			if (lengthVal >= 0 && vByteCount == lengthVal) {
				return tlByteCount + vByteCount;
			}
			vByteCount += berTag.decode(is);
		}
		
		if (lengthVal < 0) {
			if (!berTag.equals(0, 0, 0)) {
				throw new IOException("Decoded sequence has wrong end of contents octets");
			}
			vByteCount += BerLength.readEocByte(is);
			return tlByteCount + vByteCount;
		}

		throw new IOException("Unexpected end of sequence, length tag: " + lengthVal + ", bytes decoded: " + vByteCount);

	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		sb.append("\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (extensionType != null) {
			sb.append("extensionType: ").append(extensionType);
		}
		else {
			sb.append("extensionType: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (lengthh != null) {
			sb.append("lengthh: ").append(lengthh);
		}
		else {
			sb.append("lengthh: <empty-required-field>");
		}
		
		if (serviceList != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("serviceList: ");
			serviceList.appendAsString(sb, indentLevel + 1);
		}
		
		if (changeTimeList != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("changeTimeList: ");
			changeTimeList.appendAsString(sb, indentLevel + 1);
		}
		
		if (recordOpeningTime != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("recordOpeningTime: ").append(recordOpeningTime);
		}
		
		if (duration != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("duration: ").append(duration);
		}
		
		if (transparentVSA != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("transparentVSA: ").append(transparentVSA);
		}
		
		if (cdrType != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("cdrType: ").append(cdrType);
		}
		
		if (createTime != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("createTime: ").append(createTime);
		}
		
		if (chargingType != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargingType: ").append(chargingType);
		}
		
		if (roaming != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("roaming: ").append(roaming);
		}
		
		if (profile != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("profile: ").append(profile);
		}
		
		if (nsapi != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("nsapi: ").append(nsapi);
		}
		
		if (lastActivityTimeUpLink != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("lastActivityTimeUpLink: ").append(lastActivityTimeUpLink);
		}
		
		if (lastActivityTimeDownLink != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("lastActivityTimeDownLink: ").append(lastActivityTimeDownLink);
		}
		
		if (zoneId != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("zoneId: ").append(zoneId);
		}
		
		if (daylightSavingTime != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("daylightSavingTime: ").append(daylightSavingTime);
		}
		
		if (localTimeZone != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("localTimeZone: ").append(localTimeZone);
		}
		
		if (sgsnChange != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("sgsnChange: ").append(sgsnChange);
		}
		
		if (sessionID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("sessionID: ").append(sessionID);
		}
		
		if (recordOpeningTimeZone != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("recordOpeningTimeZone: ").append(recordOpeningTimeZone);
		}
		
		if (saRecordChangeTime != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("saRecordChangeTime: ").append(saRecordChangeTime);
		}
		
		if (saRecordChangeTimeZone != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("saRecordChangeTimeZone: ").append(saRecordChangeTimeZone);
		}
		
		if (acctSessionId != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("acctSessionId: ").append(acctSessionId);
		}
		
		if (acctTerminateCause != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("acctTerminateCause: ").append(acctTerminateCause);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

