/*
 * This class file was automatically generated by ASN1bean v1.12.0 (http://www.beanit.com)
 */

package pgw;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class IPTextRepresentedAddress implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	private byte[] code = null;
	private BerIA5String iPTextV4Address = null;
	private BerIA5String iPTextV6Address = null;
	
	public IPTextRepresentedAddress() {
	}

	public IPTextRepresentedAddress(byte[] code) {
		this.code = code;
	}

	public void setIPTextV4Address(BerIA5String iPTextV4Address) {
		this.iPTextV4Address = iPTextV4Address;
	}

	public BerIA5String getIPTextV4Address() {
		return iPTextV4Address;
	}

	public void setIPTextV6Address(BerIA5String iPTextV6Address) {
		this.iPTextV6Address = iPTextV6Address;
	}

	public BerIA5String getIPTextV6Address() {
		return iPTextV6Address;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			return code.length;
		}

		int codeLength = 0;
		if (iPTextV6Address != null) {
			codeLength += iPTextV6Address.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 3
			reverseOS.write(0x83);
			codeLength += 1;
			return codeLength;
		}
		
		if (iPTextV4Address != null) {
			codeLength += iPTextV4Address.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 2
			reverseOS.write(0x82);
			codeLength += 1;
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int tlvByteCount = 0;
		boolean tagWasPassed = (berTag != null);

		if (berTag == null) {
			berTag = new BerTag();
			tlvByteCount += berTag.decode(is);
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 2)) {
			iPTextV4Address = new BerIA5String();
			tlvByteCount += iPTextV4Address.decode(is, false);
			return tlvByteCount;
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 3)) {
			iPTextV6Address = new BerIA5String();
			tlvByteCount += iPTextV6Address.decode(is, false);
			return tlvByteCount;
		}

		if (tagWasPassed) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (iPTextV4Address != null) {
			sb.append("iPTextV4Address: ").append(iPTextV4Address);
			return;
		}

		if (iPTextV6Address != null) {
			sb.append("iPTextV6Address: ").append(iPTextV6Address);
			return;
		}

		sb.append("<none>");
	}

}

