/*
 * This class file was automatically generated by ASN1bean v1.12.0 (http://www.beanit.com)
 */

package pgw;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import com.beanit.asn1bean.ber.*;
import com.beanit.asn1bean.ber.types.*;
import com.beanit.asn1bean.ber.types.string.*;


public class PDPAddress implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	private byte[] code = null;
	private IPAddress iPAddress = null;
	private BerOctetString eTSIAddress = null;
	
	public PDPAddress() {
	}

	public PDPAddress(byte[] code) {
		this.code = code;
	}

	public void setIPAddress(IPAddress iPAddress) {
		this.iPAddress = iPAddress;
	}

	public IPAddress getIPAddress() {
		return iPAddress;
	}

	public void setETSIAddress(BerOctetString eTSIAddress) {
		this.eTSIAddress = eTSIAddress;
	}

	public BerOctetString getETSIAddress() {
		return eTSIAddress;
	}

	@Override public int encode(OutputStream reverseOS) throws IOException {

		if (code != null) {
			reverseOS.write(code);
			return code.length;
		}

		int codeLength = 0;
		int sublength;

		if (eTSIAddress != null) {
			codeLength += eTSIAddress.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 1
			reverseOS.write(0x81);
			codeLength += 1;
			return codeLength;
		}
		
		if (iPAddress != null) {
			sublength = iPAddress.encode(reverseOS);
			codeLength += sublength;
			codeLength += BerLength.encodeLength(reverseOS, sublength);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 0
			reverseOS.write(0xA0);
			codeLength += 1;
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	@Override public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int tlvByteCount = 0;
		boolean tagWasPassed = (berTag != null);

		if (berTag == null) {
			berTag = new BerTag();
			tlvByteCount += berTag.decode(is);
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 0)) {
			BerLength length = new BerLength();
			tlvByteCount += length.decode(is);
			iPAddress = new IPAddress();
			tlvByteCount += iPAddress.decode(is, null);
			tlvByteCount += length.readEocIfIndefinite(is);
			return tlvByteCount;
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			eTSIAddress = new BerOctetString();
			tlvByteCount += eTSIAddress.decode(is, false);
			return tlvByteCount;
		}

		if (tagWasPassed) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS);
		code = reverseOS.getArray();
	}

	@Override public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (iPAddress != null) {
			sb.append("iPAddress: ");
			iPAddress.appendAsString(sb, indentLevel + 1);
			return;
		}

		if (eTSIAddress != null) {
			sb.append("eTSIAddress: ").append(eTSIAddress);
			return;
		}

		sb.append("<none>");
	}

}

